development:
  adapter: sqlite3
  database: resume_dev
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: resume_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: resume_prod
  pool: 5
  timeout: 5000
